ifeq ($(SYNX_ROOT),)
SYNX_ROOT := $(srctree)/techpack/synx
endif

LINUXINCLUDE    += -I$(SYNX_ROOT)/include \
                   -I$(SYNX_ROOT)/include/uapi \
		   -I$(SYNX_ROOT)/include/uapi/synx/media \
		   -I$(SYNX_ROOT)/../mm/hw_fence/include/

ccflags-y += -I$(SYNX_ROOT)/msm/synx/

# add flag to compile mmrm actual implementatio instead of stub version.
# to follow up with mmrm team if techpack users need to define this for long term?
#KBUILD_CPPFLAGS += -DCONFIG_MSM_MMRM

ifeq ($(CONFIG_ARCH_WAIPIO), y)
include $(SYNX_ROOT)/config/waipiosynx.conf
LINUXINCLUDE += -include $(SYNX_ROOT)/config/waipiosynxconf.h
endif

ifeq ($(CONFIG_ARCH_KALAMA), y)
include $(SYNX_ROOT)/config/kalamasynx.conf
LINUXINCLUDE += -include $(SYNX_ROOT)/config/kalamasynxconf.h
endif

ifeq ($(CONFIG_ARCH_PINEAPPLE), y)
include $(SYNX_ROOT)/config/pineapplesynx.conf
LINUXINCLUDE += -include $(SYNX_ROOT)/config/pineapplesynxconf.h
endif

ifeq ($(CONFIG_ARCH_SUN), y)
include $(SYNX_ROOT)/config/sunsynx.conf
LINUXINCLUDE += -include $(SYNX_ROOT)/config/sunsynxconf.h
endif

obj-$(TARGET_SYNX_ENABLE) += synx-driver.o
obj-$(TARGET_SYNX_ENABLE) += synx/ipclite.o
synx-driver-objs := synx/synx.o synx/synx_global.o synx/synx_util.o synx/synx_debugfs.o \
			synx/synx_compat.o
synx-driver-$(CONFIG_DEBUG_FS) += synx/synx_debugfs_util.o
#obj-$(TARGET_SYNX_ENABLE) += synx/test/ipclite_test.o
